[workspace]
members = [
    "crates/kayton_api",
    "crates/kayton_plugin_sdk",
    "crates/kayton",
    "crates/keyton_rust_compiler",
    "crates/kayton_repl",
    "crates/kayton_vm",
    "crates/kayton_kernel",
    "crates/kayton_interactive_shared",
    "crates/kik",
]
resolver = "2"
