[workspace]
members = [
    "crates/kayton_api",
    "crates/kayton",
    "crates/plugin_hello",
    "crates/keyton_rust_compiler",
    "crates/kayton_repl",
    "crates/kayton_vm",
    "crates/kayton_kernel",
]
resolver = "2"
