[package]
name = "plugin_hello"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kayton_api = { path = "../kayton_api" }
kayton_plugin_sdk = { path = "../kayton_plugin_sdk" }