[package]
name = "kayton_interactive_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
libloading = "0.8"

# In-workspace deps
kayton_vm = { path = "../kayton_vm" }
keyton_rust_compiler = { path = "../keyton_rust_compiler" }
